name: E2E Tests
# This workflow runs end-to-end tests using Cypress
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  e2e-tests-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci
        working-directory: e2e

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e

  e2e-tests-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci
        working-directory: e2e

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e

  e2e-tests-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci
        working-directory: e2e

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e

  e2e-tests-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci
        working-directory: e2e

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e
